name: Deploy on demand
on:
  workflow_dispatch:

permissions:
  contents: write # for checkout and commit
  pull-requests: write # for create pr

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v2.3.1

      - name: 🔧 Install and Build
        run: |
          npm install
          npm run build

      - name: 🚀 Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: src # The folder the action should deploy.
